// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/analyticsv1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_analyticsv1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyticsv1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analyticsv1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	TotalClicks   int64                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	Hourly        []*HourlyBucket        `protobuf:"bytes,3,rep,name=hourly,proto3" json:"hourly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_analyticsv1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyticsv1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analyticsv1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetStatsResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *GetStatsResponse) GetHourly() []*HourlyBucket {
	if x != nil {
		return x.Hourly
	}
	return nil
}

type HourlyBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          string                 `protobuf:"bytes,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HourlyBucket) Reset() {
	*x = HourlyBucket{}
	mi := &file_proto_analyticsv1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourlyBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourlyBucket) ProtoMessage() {}

func (x *HourlyBucket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analyticsv1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourlyBucket.ProtoReflect.Descriptor instead.
func (*HourlyBucket) Descriptor() ([]byte, []int) {
	return file_proto_analyticsv1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *HourlyBucket) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *HourlyBucket) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

var File_proto_analyticsv1_analytics_proto protoreflect.FileDescriptor

const file_proto_analyticsv1_analytics_proto_rawDesc = "" +
	"\n" +
	"!proto/analyticsv1/analytics.proto\x12\fanalytics.v1\"0\n" +
	"\x0fGetStatsRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"\x88\x01\n" +
	"\x10GetStatsResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x03R\vtotalClicks\x122\n" +
	"\x06hourly\x18\x03 \x03(\v2\x1a.analytics.v1.HourlyBucketR\x06hourly\":\n" +
	"\fHourlyBucket\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\tR\x04hour\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks2]\n" +
	"\x10AnalyticsService\x12I\n" +
	"\bGetStats\x12\x1d.analytics.v1.GetStatsRequest\x1a\x1e.analytics.v1.GetStatsResponseB1Z/github.com/rajeev1818/shortly/proto/analyticsv1b\x06proto3"

var (
	file_proto_analyticsv1_analytics_proto_rawDescOnce sync.Once
	file_proto_analyticsv1_analytics_proto_rawDescData []byte
)

func file_proto_analyticsv1_analytics_proto_rawDescGZIP() []byte {
	file_proto_analyticsv1_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analyticsv1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analyticsv1_analytics_proto_rawDesc), len(file_proto_analyticsv1_analytics_proto_rawDesc)))
	})
	return file_proto_analyticsv1_analytics_proto_rawDescData
}

var file_proto_analyticsv1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_analyticsv1_analytics_proto_goTypes = []any{
	(*GetStatsRequest)(nil),  // 0: analytics.v1.GetStatsRequest
	(*GetStatsResponse)(nil), // 1: analytics.v1.GetStatsResponse
	(*HourlyBucket)(nil),     // 2: analytics.v1.HourlyBucket
}
var file_proto_analyticsv1_analytics_proto_depIdxs = []int32{
	2, // 0: analytics.v1.GetStatsResponse.hourly:type_name -> analytics.v1.HourlyBucket
	0, // 1: analytics.v1.AnalyticsService.GetStats:input_type -> analytics.v1.GetStatsRequest
	1, // 2: analytics.v1.AnalyticsService.GetStats:output_type -> analytics.v1.GetStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_analyticsv1_analytics_proto_init() }
func file_proto_analyticsv1_analytics_proto_init() {
	if File_proto_analyticsv1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analyticsv1_analytics_proto_rawDesc), len(file_proto_analyticsv1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analyticsv1_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analyticsv1_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analyticsv1_analytics_proto_msgTypes,
	}.Build()
	File_proto_analyticsv1_analytics_proto = out.File
	file_proto_analyticsv1_analytics_proto_goTypes = nil
	file_proto_analyticsv1_analytics_proto_depIdxs = nil
}
